apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flights-api
  name: flights-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flights-api
  template:
    metadata:
      labels:
        app: flights-api
    spec:
      containers:
      - image: acrpetclinic536f0e.azurecr.io/flights-api:latest
        name: flights-api
        env:
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            configMapKeyRef:
              name: flights-api
              key: APPINSIGHTS_INSTRUMENTATIONKEY
        imagePullPolicy: Always
        ports:
        - containerPort: 3003
       
   
   
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: flights-api
  name: flights-api
spec:
  ports:
  - port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    app: flights-api
  type: LoadBalancer
