apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: weather-api
  name: weather-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-api
  template:
    metadata:
      labels:
        app: weather-api
    spec:
      containers:
      - image: acrpetclinic536f0e.azurecr.io/weather-api:latest
        name: weather-api
        env:
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          valueFrom:
            configMapKeyRef:
              name: weather-api
              key: APPINSIGHTS_INSTRUMENTATIONKEY
        imagePullPolicy: Always
        ports:
        - containerPort: 3015
       
   
   
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: weather-api
  name: weather-api
spec:
  ports:
  - port: 3015
    protocol: TCP
    targetPort: 3015
  selector:
    app: weather-api
  type: LoadBalancer
